import express from "express";
import employeeRouter from "./hr/employee.js";
import departmentRouter from "./hr/department.js";
import jobListingRouter from "./hr/jobListing.js";
import jobApplicationRouter from "./hr/jobApplication.js";
import offerLetter from "./hr/offerLetter.js";
import attendanceRouter from "./hr/attendance.js";
import noticeRouter from "./hr/notice.js";
import memoRouter from "./hr/memo.js";
import projectsRouter from "./hr/projects.js";
import holidaysRouter from "./hr/holidays.js";
import listsRouter from "./hr/list.js";
import payslipRouter from "./hr/payslip.js";
import questionRouter from "./hr/question.js";
import agreementRouter from "./hr/agreement.js";
import interviewRouter from "./hr/interview.js";
import dashboardRouter from "./hr/dashboard.js";
import docsRouter from "./hr/docs.js";
import expensesRouter from "./hr/expenses.js";
import rulesRouter from "./hr/rules.js";
import awardRouter from "./hr/award.js";
import subscriptionRouter from "./hr/subscriptions.js";
import organizationRouter from "./hr/organization.js";
import messageRouter from "./hr/message.js";
import planRouter from "./hr/plan.js";
import priorityListsRouter from "./hr/priorityList.js";
import statusListRouter from "./hr/statusList.js";
import taskRouter from "./hr/task.js";
import designationRouter from "./hr/designation.js";

const router = new express.Router();

router.use("/dashboard", dashboardRouter);
router.use("/awards", awardRouter);
router.use("/employee", employeeRouter);
router.use("/department", departmentRouter);
router.use("/job-listing", jobListingRouter);
router.use("/job-application", jobApplicationRouter);
router.use("/offer-letter", offerLetter);
router.use("/agreement", agreementRouter);
router.use("/expenses", expensesRouter);
router.use("/attendance", attendanceRouter);
router.use("/notice", noticeRouter);
router.use("/memo", memoRouter);
router.use("/docs", docsRouter);
router.use("/projects", projectsRouter);
router.use("/holidays", holidaysRouter);
router.use("/lists", listsRouter);
router.use("/payslip", payslipRouter);
router.use("/question", questionRouter);
router.use("/interview", interviewRouter);
router.use("/rules", rulesRouter);
router.use("/plan", planRouter);
router.use("/subscription", subscriptionRouter);
router.use("/organization", organizationRouter);
router.use("/message", messageRouter);
router.use("/priority-list", priorityListsRouter);
router.use("/status-list", statusListRouter);
router.use("/task", taskRouter);
router.use("/designation", designationRouter);

export default router;
